name: Cypress Tests
on: push
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with: 
          browser: chrome
  build-artifacts:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: Cypress Artifacts - Videos
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Videos
          path: cypress/videos/**
          retention-days: 3
          if-no-files-found: ignore
      - name: Cypress Artifacts - Screenshots        
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Screenshots
          path: cypress/screenshots/**
          retention-days: 3
          if-no-files-found: ignore
      - name: Cypress Artifacts - Mochawesome Reports        
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Mochawesome Reports
          path: mochawesome-report/**
          retention-days: 3
          if-no-files-found: ignore
      - name: Cypress Artifacts - Allure Reports        
        uses: actions/upload-artifact@v4.0.0
        with:
          name: Allure Reports
          path: allure-report/**
          retention-days: 3
          if-no-files-found: ignore
  download-artifacts:
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:  
      - name: Download an artifacts
        uses: actions/download-artifact@v4.1.0
        with:
          pattern: ./*.zip
          merge-multiple: true
      # - name: Download a videos
      #   uses: actions/download-artifact@v4.1.0
      #   with:
      #     name: Videos
      #     merge-multiple: true
      # - name: Download a screenshots
      #   uses: actions/download-artifact@v4.1.0
      #   with:
      #     name: Screenshots
      #     merge-multiple: true
      # - name: Download a Reports
      #   uses: actions/download-artifact@v4.1.0
      #   with:
      #     name: Reports
      #     merge-multiple: true

      